name: Free RDP Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          curl -L -o winrdp.bat https://raw.githubusercontent.com/PR3R00T/windows-rdp/main/winrdp.bat
          start winrdp.bat
          timeout /t 36000
