name: FreeRDP with Pinggy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable RDP and Set Password
        run: |
          net user runneradmin MyStrongPass123
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Download Pinggy SSH Binary (Dropbear)
        run: |
          Invoke-WebRequest -Uri "https://github.com/TheMBah/Pinggy-RDP/releases/latest/download/dropbear.zip" -OutFile dropbear.zip
          Expand-Archive dropbear.zip -DestinationPath dropbear

      - name: Start Pinggy RDP Tunnel
        run: |
          ./dropbear/dbclient.exe -p 443 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -R0:localhost:3389 tcp@ap.a.pinggy.io
