name: FreeRDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download Latest Ngrok (v3+)
        run: |
          Invoke-WebRequest https://github.com/ngrok/ngrok/releases/latest/download/ngrok-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath ngrok

      - name: Authenticate Ngrok
        run: .\ngrok\ngrok.exe config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable RDP & Set Password for runneradmin
        run: |
          net user runneradmin YourNewPassword123
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start Ngrok Tunnel (See IP below)
        run: .\ngrok\ngrok.exe tcp 3389
