name: FreeRDP via Pinggy SSH

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable RDP and Set Password
        run: |
          net user runneradmin MyStrongPass123
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start Pinggy Tunnel via SSH
        shell: powershell
        run: |
          Start-Process powershell -WindowStyle Hidden -ArgumentList @"
          ssh -p 443 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -R0:localhost:3389 tcp@ap.a.pinggy.io
"@
